spring:
  application:
    name: JournalApp
  data:
    mongodb:
      uri: mongodb+srv://aniruddhabiswas105:ZGyki101RlwOR30w@cluster0.nifrc.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: springDB
      auto-index-creation: true

server:
  port: 8080
  servlet:
    context-path: /journal